const mainMenuList = [
  "寿司",
  "天ぷら",
  "そば",
  "うどん",
  "おでん",
  "お好み焼き",
  "焼き魚",
  "味噌汁",
  "納豆ご飯",
  "たこ焼き",
  "牛丼",
  "親子丼",
  "カツ丼",
  "鯖の塩焼き",
  "煮物",
  "すき焼き",
  "しゃぶしゃぶ",
  "茶碗蒸し",
  "ひじきの煮物",
  "ピザ",
  "パスタ",
  "ハンバーガー",
  "ステーキ",
  "オムレツ",
  "カルボナーラ",
  "ボロネーゼ",
  "クラブサンドイッチ",
  "シーザーサラダ",
  "クリームシチュー",
  "フィッシュ＆チップス",
  "ミートローフ",
  "フリッタータ",
  "グラタン",
  "チキンパルメザン",
  "クスクス",
  "餃子",
  "小籠包",
  "麻婆豆腐",
  "酢豚",
  "エビチリ",
  "青椒肉絲",
  "回鍋肉",
  "担々麺",
  "春巻き",
  "北京ダック",
  "フカヒレスープ",
  "ワンタン麺",
  "チャーハン",
  "八宝菜",
  "牛肉とブロッコリーの炒め物",
  "キムチチゲ",
  "ビビンバ",
  "サムギョプサル",
  "トッポギ",
  "ユッケジャン",
  "プルコギ",
  "キンパ",
  "チヂミ",
  "カルビクッパ",
  "サムゲタン",
  "タコス",
  "ブリトー",
  "フェイジョアーダ",
  "ガパオライス",
  "トムヤムクン",
  "フォー",
  "バインミー",
  "チキンティッカマサラ",
  "バターチキンカレー",
  "ナシゴレン"
];

const dessertMenuList = [
  "チーズケーキ",
  "ショートケーキ",
  "ティラミス",
  "クレームブリュレ",
  "パンナコッタ",
  "アイスクリーム",
  "パフェ",
  "和風パフェ",
  "大福",
  "どら焼き",
  "白玉ぜんざい",
  "プリン",
  "ガトーショコラ",
  "モンブラン",
  "タルトタタン"
];

document.getElementById('mainGachaButton').addEventListener('click', () => {
  const randomIndex = Math.floor(Math.random() * mainMenuList.length);
  const randomMenu = mainMenuList[randomIndex];
  document.getElementById('mainResult').textContent = `今日のメインメニューは: ${randomMenu}`;
});

document.getElementById('dessertGachaButton').addEventListener('click', () => {
  const randomIndex = Math.floor(Math.random() * dessertMenuList.length);
  const randomDessert = dessertMenuList[randomIndex];
  document.getElementById('dessertResult').textContent = `今日のデザートは: ${randomDessert}`;
});
